import { ThemeDefSchema } from '@plexus/shared';
import { BUILTIN_THEMES, DEFAULT_DARK_THEME_ID } from './builtin';
import { compileTheme } from './compile';

export const GENERATED_CSS_HEADER =
  '/* GENERATED by scripts/gen-theme-css.ts from src/theme/builtin — do not edit. Run: bun run gen:themes */';

/**
 * Static CSS for every built-in theme. plexus-dark comes first and doubles as
 * the :where(:root) fallback for unknown theme ids. The zero-specificity root
 * keeps it from overriding a custom theme's rule injected earlier in <head>.
 */
export function buildBuiltinThemesCss(): string {
  const defs = BUILTIN_THEMES.map((d) => ThemeDefSchema.parse(d));
  const dark = defs.find((d) => d.id === DEFAULT_DARK_THEME_ID);
  if (!dark) throw new Error(`Missing default dark theme "${DEFAULT_DARK_THEME_ID}"`);
  const blocks = [
    compileTheme(dark, { selector: `:where(:root), [data-theme="${DEFAULT_DARK_THEME_ID}"]` }).css,
    ...defs.filter((d) => d.id !== DEFAULT_DARK_THEME_ID).map((d) => compileTheme(d).css),
  ];
  return `${GENERATED_CSS_HEADER}\n\n${blocks.map((b) => b.trimEnd()).join('\n\n')}\n`;
}
